#!/bin/bash

##
## A generic script to modify a version number.
##
## Examples:
## update-version 1.2.3 #> 1.2.3
## update-version 1.2.3 +patch #> 1.2.4
## update-version 1.2.3 +major +minor +patch > 2.3.4
##
## Modifiers can be in the version number to alter output.
##
## Modifiers override +major, +minor and +patch
##
## # zero reset modifier (~) - reset a component to 0
## update-version 1.2.~ #> 1.2.0
## update-version ~.~.~ #> 0.0.0
## update-version 1.~.3 #> 1.0.3
## update-version 1.~.3 +patch #>1.0.3
## 
## # force modifier (!) - don't update anything
## update-version !2.0.0 #> 2.0.0
## update-version !1.2.3 #> 1.2.3
## update-version !2.3.0 +patch #> 2.3.0
##
## # Version tags are allowed
## 
## update-version 1.2.3-alpha1 +patch #> 1.2.4-alpha1
## update-version 1.~.3-alpha1 +patch #> 1.0.4-alpha1
## update-version !1.~.~ #> 1.0.0
##
## ## Printing Version Info
##
## update-version 1.2.3 --print-minor #> 2
## update-version 1.2.3 --print-major #> 1
## update-version 1.2.3 --print-patch #> 3
## update-version 1.2.3-alpha1 --print-tag #> -alpha1
##

#modifier characters
FORCE_MODIFIER="!"
ZERO_MODIFIER="~"

getShebang() {
	if [ -z "$1" ]; then
		echo ''
		return
	fi
	version=$1
	shebang=$(echo $version | python -c '
import re,sys;patch=re.search("^('"${FORCE_MODIFIER}"')?",sys.stdin.read());
if patch.group(1): print patch.group(1)
else: print ''')
	echo $shebang
}

getMajor() {
	if [ -z "$1" ]; then
		echo ''
		return
	fi
	version=$1
	major=$(echo $version | python -c '
import re,sys;patch=re.search("^('"${FORCE_MODIFIER}"')?([0-9]*'"${ZERO_MODIFIER}"'?)\.",sys.stdin.read());
print patch.group(2)')
	echo $major
}

getMinor() {
	if [ -z "$1" ]; then
		echo ''
		return
	fi
	version=$1
	minor=$(echo $version | python -c '
import re,sys;patch=re.search("^('"${FORCE_MODIFIER}"')?([0-9]*'"${ZERO_MODIFIER}"'?)\.([0-9]*'"${ZERO_MODIFIER}"'?)\.",sys.stdin.read());
print patch.group(3)')
	echo $minor
}

getPatch() {
	if [ -z "$1" ]; then
		echo ''
		return
	fi
	version=$1
	patch=$(echo $version | python -c '
import re,sys;
patch=re.search("^('"${FORCE_MODIFIER}"')?([0-9]*'"${ZERO_MODIFIER}"'?)\.([0-9]*'"${ZERO_MODIFIER}"'?)\.([0-9]*'"${ZERO_MODIFIER}"'?)",sys.stdin.read());
print patch.group(4)')
	echo $patch
}

getTag() {
	if [ -z "$1" ]; then
		echo ''
		return
	fi
	version=$1
	tag=$(echo $version | python -c '
import re,sys;
patch=re.search("('"${FORCE_MODIFIER}"')?([0-9]*'"${ZERO_MODIFIER}"'?)\.([0-9]*'"${ZERO_MODIFIER}"'?)\.([0-9]*'"${ZERO_MODIFIER}"'?)([\-|\+0-9a-zA-Z\.\-\_]*)?",sys.stdin.read());
print patch.group(5)')
	echo $tag
}

assert() {
	echo "assert $1 == $2"
	if [ "$1" != "$2" ]; then
		echo "Assert fail $1 != $2"
		exit 1
	fi
}

if [ "$1" = '--tests' ] || [ "$1" = '--test' ]; then
	echo "Testing..."

	VERSION='1.2.3'
	MAJOR=$(getMajor $VERSION)
	MINOR=$(getMinor $VERSION)
	PATCH=$(getPatch $VERSION)
	TAG=$(getTag $VERSION)
	assert $MAJOR '1'
	assert $MINOR '2'
	assert $PATCH '3'
	assert $TAG ''

	VERSION='1.2.3-alpha'
	MAJOR=$(getMajor $VERSION)
	MINOR=$(getMinor $VERSION)
	PATCH=$(getPatch $VERSION)
	TAG=$(getTag $VERSION)
	assert $MAJOR '1'
	assert $MINOR '2'
	assert $PATCH '3'
	assert $TAG '-alpha'

	VERSION='10.2.30+'
	MAJOR=$(getMajor $VERSION)
	MINOR=$(getMinor $VERSION)
	PATCH=$(getPatch $VERSION)
	TAG=$(getTag $VERSION)
	assert $MAJOR '10'
	assert $MINOR '2'
	assert $PATCH '30'
	assert $TAG '+'

	VERSION='10.2.30-'
	MAJOR=$(getMajor $VERSION)
	MINOR=$(getMinor $VERSION)
	PATCH=$(getPatch $VERSION)
	TAG=$(getTag $VERSION)
	assert $MAJOR '10'
	assert $MINOR '2'
	assert $PATCH '30'
	assert $TAG '-'

	VERSION='10.2.30-alpha'
	MAJOR=$(getMajor $VERSION)
	MINOR=$(getMinor $VERSION)
	PATCH=$(getPatch $VERSION)
	TAG=$(getTag $VERSION)
	assert $MAJOR '10'
	assert $MINOR '2'
	assert $PATCH '30'
	assert $TAG '-alpha'

	VERSION='10.2.30+alpha'
	MAJOR=$(getMajor $VERSION)
	MINOR=$(getMinor $VERSION)
	PATCH=$(getPatch $VERSION)
	TAG=$(getTag $VERSION)
	assert $MAJOR '10'
	assert $MINOR '2'
	assert $PATCH '30'
	assert $TAG '+alpha'

	VERSION="1.2.3-alpha+rc1"
	MAJOR=$(getMajor $VERSION)
	MINOR=$(getMinor $VERSION)
	PATCH=$(getPatch $VERSION)
	TAG=$(getTag $VERSION)
	assert $MAJOR '1'
	assert $MINOR '2'
	assert $PATCH '3'
	assert $TAG '-alpha+rc1'

	VERSION="1.2.3-alpha+rc1.808"
	MAJOR=$(getMajor $VERSION)
	MINOR=$(getMinor $VERSION)
	PATCH=$(getPatch $VERSION)
	TAG=$(getTag $VERSION)
	assert $MAJOR '1'
	assert $MINOR '2'
	assert $PATCH '3'
	assert $TAG '-alpha+rc1.808'

	VERSION="1.2.3+alpha-rc1.808"
	MAJOR=$(getMajor $VERSION)
	MINOR=$(getMinor $VERSION)
	PATCH=$(getPatch $VERSION)
	TAG=$(getTag $VERSION)
	assert $MAJOR '1'
	assert $MINOR '2'
	assert $PATCH '3'
	assert $TAG '+alpha-rc1.808'

	VERSION="1.2.3+alpha-rc1.808_beta"
	MAJOR=$(getMajor $VERSION)
	MINOR=$(getMinor $VERSION)
	PATCH=$(getPatch $VERSION)
	TAG=$(getTag $VERSION)
	assert $MAJOR '1'
	assert $MINOR '2'
	assert $PATCH '3'
	assert $TAG '+alpha-rc1.808_beta'

	VERSION="1.2.3+alpha-rc1.808-beta"
	MAJOR=$(getMajor $VERSION)
	MINOR=$(getMinor $VERSION)
	PATCH=$(getPatch $VERSION)
	TAG=$(getTag $VERSION)
	assert $MAJOR '1'
	assert $MINOR '2'
	assert $PATCH '3'
	assert $TAG '+alpha-rc1.808-beta'

	VERSION="1.2.3-alpha-rc1"
	MAJOR=$(getMajor $VERSION)
	MINOR=$(getMinor $VERSION)
	PATCH=$(getPatch $VERSION)
	TAG=$(getTag $VERSION)
	assert $MAJOR '1'
	assert $MINOR '2'
	assert $PATCH '3'
	assert $TAG '-alpha-rc1'

	VERSION="1.2.3-alpha.10"
	MAJOR=$(getMajor $VERSION)
	MINOR=$(getMinor $VERSION)
	PATCH=$(getPatch $VERSION)
	TAG=$(getTag $VERSION)
	assert $MAJOR '1'
	assert $MINOR '2'
	assert $PATCH '3'
	assert $TAG '-alpha.10'

	VERSION='10.2.3'
	MAJOR=$(getMajor $VERSION)
	MINOR=$(getMinor $VERSION)
	PATCH=$(getPatch $VERSION)
	TAG=$(getTag $VERSION)
	assert $MAJOR '10'
	assert $MINOR '2'
	assert $PATCH '3'
	assert $TAG ''

	VERSION='100.200.300'
	MAJOR=$(getMajor $VERSION)
	MINOR=$(getMinor $VERSION)
	PATCH=$(getPatch $VERSION)
	TAG=$(getTag $VERSION)
	assert $MAJOR '100'
	assert $MINOR '200'
	assert $PATCH '300'
	assert $TAG ''

	VERSION='1000000.2000000.300000'
	MAJOR=$(getMajor $VERSION)
	MINOR=$(getMinor $VERSION)
	PATCH=$(getPatch $VERSION)
	TAG=$(getTag $VERSION)
	assert $MAJOR '1000000'
	assert $MINOR '2000000'
	assert $PATCH '300000'
	assert $TAG ''

	VERSION='1000000.2000000.300000+alpha1-beta06.9DS0DLW'
	MAJOR=$(getMajor $VERSION)
	MINOR=$(getMinor $VERSION)
	PATCH=$(getPatch $VERSION)
	TAG=$(getTag $VERSION)
	assert $MAJOR '1000000'
	assert $MINOR '2000000'
	assert $PATCH '300000'
	assert $TAG '+alpha1-beta06.9DS0DLW'

	VERSION='10.20.30'
	MAJOR=$(getMajor $VERSION)
	MINOR=$(getMinor $VERSION)
	PATCH=$(getPatch $VERSION)
	TAG=$(getTag $VERSION)
	assert $MAJOR '10'
	assert $MINOR '20'
	assert $PATCH '30'
	assert $TAG ''

	VERSION='10.2.30'
	MAJOR=$(getMajor $VERSION)
	MINOR=$(getMinor $VERSION)
	PATCH=$(getPatch $VERSION)
	TAG=$(getTag $VERSION)
	assert $MAJOR '10'
	assert $MINOR '2'
	assert $PATCH '30'
	assert $TAG ''

	VERSION='10.2.30+-alpha'
	MAJOR=$(getMajor $VERSION)
	MINOR=$(getMinor $VERSION)
	PATCH=$(getPatch $VERSION)
	TAG=$(getTag $VERSION)
	assert $MAJOR '10'
	assert $MINOR '2'
	assert $PATCH '30'
	assert $TAG '+-alpha'

	VERSION='10.2.30+-alpha.01rc-alpha'
	MAJOR=$(getMajor $VERSION)
	MINOR=$(getMinor $VERSION)
	PATCH=$(getPatch $VERSION)
	TAG=$(getTag $VERSION)
	assert $MAJOR '10'
	assert $MINOR '2'
	assert $PATCH '30'
	assert $TAG '+-alpha.01rc-alpha'

	VERSION='10.2.300'
	MAJOR=$(getMajor $VERSION)
	MINOR=$(getMinor $VERSION)
	PATCH=$(getPatch $VERSION)
	TAG=$(getTag $VERSION)
	assert $MAJOR '10'
	assert $MINOR '2'
	assert $PATCH '300'
	assert $TAG ''

	VERSION='100.200.300'
	MAJOR=$(getMajor $VERSION)
	MINOR=$(getMinor $VERSION)
	PATCH=$(getPatch $VERSION)
	TAG=$(getTag $VERSION)
	assert $MAJOR '100'
	assert $MINOR '200'
	assert $PATCH '300'
	assert $TAG ''

	VERSION='100.200.300-alpha-1'
	MAJOR=$(getMajor $VERSION)
	MINOR=$(getMinor $VERSION)
	PATCH=$(getPatch $VERSION)
	TAG=$(getTag $VERSION)
	assert $MAJOR '100'
	assert $MINOR '200'
	assert $PATCH '300'
	assert $TAG '-alpha-1'

	VERSION="1.2.${ZERO_MODIFIER}"
	MAJOR=$(getMajor $VERSION)
	MINOR=$(getMinor $VERSION)
	PATCH=$(getPatch $VERSION)
	TAG=$(getTag $VERSION)
	assert $MAJOR '1'
	assert $MINOR '2'
	assert $PATCH ${ZERO_MODIFIER}
	assert $TAG ''

	VERSION="1.2.${ZERO_MODIFIER}-alpha1"
	MAJOR=$(getMajor $VERSION)
	MINOR=$(getMinor $VERSION)
	PATCH=$(getPatch $VERSION)
	TAG=$(getTag $VERSION)
	assert $MAJOR '1'
	assert $MINOR '2'
	assert $PATCH ${ZERO_MODIFIER}
	assert $TAG '-alpha1'

	VERSION="1.${ZERO_MODIFIER}.1"
	MAJOR=$(getMajor $VERSION)
	MINOR=$(getMinor $VERSION)
	PATCH=$(getPatch $VERSION)
	TAG=$(getTag $VERSION)
	assert $MAJOR '1'
	assert $MINOR ${ZERO_MODIFIER}
	assert $PATCH '1'
	assert $TAG ''

	VERSION="1.${ZERO_MODIFIER}.1-alpha2"
	MAJOR=$(getMajor $VERSION)
	MINOR=$(getMinor $VERSION)
	PATCH=$(getPatch $VERSION)
	TAG=$(getTag $VERSION)
	assert $MAJOR '1'
	assert $MINOR ${ZERO_MODIFIER}
	assert $PATCH '1'
	assert $TAG '-alpha2'

	VERSION="1.${ZERO_MODIFIER}.${ZERO_MODIFIER}-alpha2"
	MAJOR=$(getMajor $VERSION)
	MINOR=$(getMinor $VERSION)
	PATCH=$(getPatch $VERSION)
	TAG=$(getTag $VERSION)
	assert $MAJOR '1'
	assert $MINOR ${ZERO_MODIFIER}
	assert $PATCH ${ZERO_MODIFIER}
	assert $TAG '-alpha2'

	VERSION="${FORCE_MODIFIER}1.${ZERO_MODIFIER}.${ZERO_MODIFIER}-alpha2"
	SHEBANG=$(getShebang $VERSION)
	MAJOR=$(getMajor $VERSION)
	MINOR=$(getMinor $VERSION)
	PATCH=$(getPatch $VERSION)
	TAG=$(getTag $VERSION)
	assert $SHEBANG ${FORCE_MODIFIER}
	assert $MAJOR '1'
	assert $MINOR ${ZERO_MODIFIER}
	assert $PATCH ${ZERO_MODIFIER}
	assert $TAG '-alpha2'

	VERSION='1.0.0-beta+exp.sha.5114f85'
	SHEBANG=$(getShebang $VERSION)
	MAJOR=$(getMajor $VERSION)
	MINOR=$(getMinor $VERSION)
	PATCH=$(getPatch $VERSION)
	TAG=$(getTag $VERSION)
	assert $SHEBANG ''
	assert $MAJOR '1'
	assert $MINOR '0'
	assert $PATCH '0'
	assert $TAG '-beta+exp.sha.5114f85'

	VERSION='1.0.0+20130313144700'
	SHEBANG=$(getShebang $VERSION)
	MAJOR=$(getMajor $VERSION)
	MINOR=$(getMinor $VERSION)
	PATCH=$(getPatch $VERSION)
	TAG=$(getTag $VERSION)
	assert $SHEBANG ''
	assert $MAJOR '1'
	assert $MINOR '0'
	assert $PATCH '0'
	assert $TAG '+20130313144700'

	VERSION="1.${ZERO_MODIFIER}.${ZERO_MODIFIER}-beta+exp.sha.5114f85"
	SHEBANG=$(getShebang $VERSION)
	MAJOR=$(getMajor $VERSION)
	MINOR=$(getMinor $VERSION)
	PATCH=$(getPatch $VERSION)
	TAG=$(getTag $VERSION)
	assert $SHEBANG ''
	assert $MAJOR '1'
	assert $MINOR ${ZERO_MODIFIER}
	assert $PATCH ${ZERO_MODIFIER}
	assert $TAG '-beta+exp.sha.5114f85'

	VERSION="${FORCE_MODIFIER}1.${ZERO_MODIFIER}.${ZERO_MODIFIER}-beta+exp.sha.5114f85"
	SHEBANG=$(getShebang $VERSION)
	MAJOR=$(getMajor $VERSION)
	MINOR=$(getMinor $VERSION)
	PATCH=$(getPatch $VERSION)
	TAG=$(getTag $VERSION)
	assert $SHEBANG ${FORCE_MODIFIER}
	assert $MAJOR '1'
	assert $MINOR ${ZERO_MODIFIER}
	assert $PATCH ${ZERO_MODIFIER}
	assert $TAG '-beta+exp.sha.5114f85'

	output=$(./$0 1.2.3)
	assert $output "1.2.3"

	output=$(./$0 10.10.10+)
	assert $output "10.10.10+"

	output=$(./$0 10.10.10+ +patch)
	assert $output "10.10.11+"

	output=$(./$0 10.10.10- +patch)
	assert $output "10.10.11-"

	output=$(./$0 1.3.4-alpha1 +patch)
	assert $output "1.3.5-alpha1"

	output=$(./$0 1.2.3 +major +minor +patch)
	assert $output "2.3.4"

	output=$(./$0 "${FORCE_MODIFIER}1.${ZERO_MODIFIER}.2" +minor)
	assert $output "1.0.2"

	output=$(./$0 "${FORCE_MODIFIER}${ZERO_MODIFIER}.${ZERO_MODIFIER}.${ZERO_MODIFIER}" +major +minor +patch)
	assert $output "0.0.0"

	output=$(./$0 "${FORCE_MODIFIER}${ZERO_MODIFIER}.${ZERO_MODIFIER}.${ZERO_MODIFIER}" +major)
	assert $output "0.0.0"

	output=$(./$0 "${FORCE_MODIFIER}${ZERO_MODIFIER}.${ZERO_MODIFIER}.${ZERO_MODIFIER}" +major +minor)
	assert $output "0.0.0"

	output=$(./$0 "${FORCE_MODIFIER}${ZERO_MODIFIER}.${ZERO_MODIFIER}.${ZERO_MODIFIER}" +minor)
	assert $output "0.0.0"

	output=$(./$0 "${FORCE_MODIFIER}${ZERO_MODIFIER}.${ZERO_MODIFIER}.${ZERO_MODIFIER}" +minor +patch)
	assert $output "0.0.0"

	output=$(./$0 "${FORCE_MODIFIER}${ZERO_MODIFIER}.${ZERO_MODIFIER}.${ZERO_MODIFIER}" +patch)
	assert $output "0.0.0"

	output=$(./$0 10.10.10)
	assert $output "10.10.10"

	output=$(./$0 2.3.4-alpha1.beta2-98ad873 +patch)
	assert $output "2.3.5-alpha1.beta2-98ad873"
	
	output=$(./$0 2.3.4-alpha1.beta2-98ad873 +patch +major)
	assert $output "3.3.5-alpha1.beta2-98ad873"

	output=$(./$0 2.3.4-alpha1.beta2-98ad873 +patch +major +minor)
	assert $output "3.4.5-alpha1.beta2-98ad873"

	output=$(./$0 "${FORCE_MODIFIER}2.3.4-alpha1.beta2-98ad873" +patch +major +minor)
	assert $output "2.3.4-alpha1.beta2-98ad873"

	output=$(./$0 "${ZERO_MODIFIER}.${ZERO_MODIFIER}.${ZERO_MODIFIER}-alpha1.beta2-98ad873" +patch +major +minor)
	assert $output "0.0.0-alpha1.beta2-98ad873"

	output=$(./$0 "${ZERO_MODIFIER}.2.${ZERO_MODIFIER}-alpha1.beta2-98ad873" +patch +major +minor)
	assert $output "0.3.0-alpha1.beta2-98ad873"

	output=$(./$0 "${ZERO_MODIFIER}.2.${ZERO_MODIFIER}-alpha1.beta2-98ad873" +patch)
	assert $output "0.2.0-alpha1.beta2-98ad873"

	output=$(./$0 "${FORCE_MODIFIER}${ZERO_MODIFIER}.${ZERO_MODIFIER}.${ZERO_MODIFIER}-alpha1.beta2-98ad873" +patch +major +minor)
	assert $output "0.0.0-alpha1.beta2-98ad873"

	output=$(./$0 '1.2.3' ^patch)
	assert $output "1.2.4"

	output=$(./$0 '1.2.3' ^patch ^minor ^major)
	assert $output "2.3.4"

	output=$(./$0 '1.2.3+alpha.04' +minor)
	assert $output "1.3.3+alpha.04"

	output=$(./$0 1.2.3)
	assert $output "1.2.3"

	output=$(./$0 1.~.~ +patch +minor +major)
	assert $output "2.0.0"

	output=$(./$0 "~.~.~" +patch +minor +major)
	assert $output "0.0.0"

	output=$(./$0  "1.2.3" --print-patch)
	assert $output "3"

	output=$(./$0  "1.2.3" --print-major)
	assert $output "1"

	output=$(./$0  "1.2.3" --print-minor)
	assert $output "2"

	output=$(./$0  "1.2.3-alpha1.0934" --print-tag)
	assert $output "-alpha1.0934"

	echo "all tests passed"
	exit
fi

#grab version from args
VERSION=$1
#TODO: Validate VERSION matches regex

#set default vars
INC_MAJOR=false
INC_MINOR=false
INC_PATCH=false

#print vars
PRINT_MAJOR=false
PRINT_MINOR=false
PRINT_PATCH=false
PRINT_TAG=false

#parse args
for i in "$@"
do
	case "$i" in
	+major|^major)
		INC_MAJOR=true
		;;
	+minor|^minor)
		INC_MINOR=true
		;;
	+patch|^patch)
		INC_PATCH=true
		;;
	--print-major)
		PRINT_MAJOR=true
		break
		;;
	--print-minor)
		PRINT_MINOR=true
		break
		;;
	--print-patch)
		PRINT_PATCH=true
		break
		;;
	--print-tag)
		PRINT_TAG=true
		break
		;;
	esac
done

#grab components from version
SHEBANG=$(getShebang $VERSION)
MAJOR=$(getMajor $VERSION)
MINOR=$(getMinor $VERSION)
PATCH=$(getPatch $VERSION)
TAG=$(getTag $VERSION)

if [ "$PRINT_MAJOR" = true ]; then
	echo $MAJOR
	exit 0;
fi

if [ "$PRINT_MINOR" = true ]; then
	echo $MINOR
	exit 0
fi

if [ "$PRINT_PATCH" = true ]; then
	echo $PATCH
	exit 0
fi

if [ "$PRINT_TAG" = true ]; then
	echo $TAG
	exit 0
fi

NEW_MAJOR=$MAJOR
NEW_MINOR=$MINOR
NEW_PATCH=$PATCH
MAJOR_ZEROED=''
MINOR_ZEROED=''
PATCH_ZEROED=''

#check for ~ to reset major to 0
if [ "${MAJOR}" = "${ZERO_MODIFIER}" ]; then
	NEW_MAJOR='0'
	MAJOR_ZEROED='true'
fi

#check for ~ to reset minor to 0
if [ "${MINOR}" = "${ZERO_MODIFIER}" ]; then
	NEW_MINOR='0'
	MINOR_ZEROED='true'
fi

#check for ~ to reset patch to 0
if [ "${NEW_PATCH}" = "${ZERO_MODIFIER}" ]; then
	NEW_PATCH='0'
	PATCH_ZEROED='true'
fi

#increment major if shebang isn't present
if [ "$INC_MAJOR" = 'true' ] && [ -z $SHEBANG ] && [ -z $MAJOR_ZEROED ]; then
	NEW_MAJOR=$(($NEW_MAJOR + 1))
fi

#increment minor if shebang isn't present
if [ "$INC_MINOR" = 'true' ] && [ -z $SHEBANG ] && [ -z $MINOR_ZEROED ]; then
	NEW_MINOR=$(($NEW_MINOR + 1))
fi

#increment patch if shebang isn't present
if [ "$INC_PATCH" = "true" ] && [ -z $SHEBANG ] && [ -z $PATCH_ZEROED ]; then
	NEW_PATCH=$(($NEW_PATCH + 1))
fi

#create new version
if [ "${TAG}" ]; then
	echo "${NEW_MAJOR}.${NEW_MINOR}.${NEW_PATCH}${TAG}"
else
	echo "${NEW_MAJOR}.${NEW_MINOR}.${NEW_PATCH}"
fi
