#!/bin/bash

##
## A generic script to modify a version number.
##
## Examples:
## update-version 1.2.3 #> 1.2.3
## update-version 1.2.3 +patch #> 1.2.4
## update-version 1.2.3 +major +minor +patch > 2.3.4
## 
## Modifiers can be in the version number to alter output.
##
## Modifiers override +major, +minor and +patch
##
## # zero reset modifier (~) - reset a component to 0
## update-version 1.2.~ #> 1.2.0
## update-version ~.~.~ #> 0.0.0
## update-version 1.~.3 #> 1.0.3
## update-version 1.~.3 +patch #>1.0.3
## 
## # force modifier (!) - don't update anything
## update-version !2.0.0 #> 2.0.0
## update-version !1.2.3 #> 1.2.3
## update-version !2.3.0 +patch #> 2.3.0
##
## # Version tags are allowed
## 
## update-version 1.2.3-alpha1 +patch #> 1.2.4-alpha1
## update-version 1.~.3-alpha1 +patch #> 1.0.4-alpha1
## update-version !1.~.~ #> 1.0.0
##
## ## Printing Version Info
## 
## update-version 1.2.3 --print-minor #> 2
## update-version 1.2.3 --print-major #> 1
## update-version 1.2.3 --print-patch #> 3
## update-version 1.2.3-alpha1 --print-tag #> -alpha1
##
## ## Printing with Modifiers
##
## Modifiers are applied before printing a component.
##
## update-version 1.2.3 --print-minor +minor #> 3
## update-version 1.~.3 --print-minor +minor #> 0
## update-version !1.2.3 --print-minor +minor #> 2
##

output_help() {
	##
echo ""
echo "#A generic script to modify a version number.
update-version 1.2.3 #> 1.2.3
update-version 1.2.3 +patch #> 1.2.4
update-version 1.2.3 +major +minor +patch > 2.3.4

# Modifiers can be in the version number to alter output.

# Modifiers override +major, +minor and +patch

# zero reset modifier (~) - reset a component to 0
update-version 1.2.~ #> 1.2.0
update-version ~.~.~ #> 0.0.0
update-version 1.~.3 #> 1.0.3
update-version 1.~.3 +patch #>1.0.3

# force modifier (!) - don't update anything

update-version !2.0.0 #> 2.0.0
update-version !1.2.3 #> 1.2.3
update-version !2.3.0 +patch #> 2.3.0

# Version tags are allowed

update-version 1.2.3-alpha1 +patch #> 1.2.4-alpha1
update-version 1.~.3-alpha1 +patch #> 1.0.4-alpha1
update-version !1.~.~ #> 1.0.0

# Printing Version Info

update-version 1.2.3 --print-minor #> 2
update-version 1.2.3 --print-major #> 1
update-version 1.2.3 --print-patch #> 3
update-version 1.2.3-alpha1 --print-tag #> -alpha1

# Printing with Modifiers

# Modifiers are applied before printing a component.

update-version 1.2.3 --print-minor +minor #> 3
update-version 1.~.3 --print-minor +minor #> 0
update-version !1.2.3 --print-minor +minor #> 2"
}

getForce() {
	if [ -z "$1" ]; then
		echo ''
		return
	fi
	force=''
	version=$1
	regex="^(!)?"
	if [[ $version =~ $regex ]]; then
		force="${BASH_REMATCH[1]}"
	fi
	echo $force
}

getMajor() {
	if [ -z "$1" ]; then
		echo ''
		return
	fi
	major=''
	version=$1
	regex="^(!)?([0-9]*|~?)\."
	if [[ $version =~ $regex ]]; then
		major="${BASH_REMATCH[2]}"
	fi
	echo $major
}

getMinor() {
	if [ -z "$1" ]; then
		echo ''
		return
	fi
	minor=''
	version=$1
	regex="^(!)?([0-9]*|~?)\.([0-9]*|~?)\."
	if [[ $version =~ $regex ]]; then
		minor="${BASH_REMATCH[3]}"
	fi
	echo $minor
}

getPatch() {
	if [ -z "$1" ]; then
		echo ''
		return
	fi
	patch=''
	version=$1
	regex="^(!)?([0-9]*|~?)\.([0-9]*|~?)\.([0-9]*|~?)"
	if [[ $version =~ $regex ]]; then
		patch="${BASH_REMATCH[4]}"
	fi
	echo $patch
}

getTag() {
	if [ -z "$1" ]; then
		echo ''
		return
	fi
	tag=''
	version=$1
	regex="^(!)?([0-9]*|~?)\.([0-9]*|~?)\.([0-9]*|~?)([-+0-9a-zA-Z\_\.]*)?"
	if [[ $version =~ $regex ]]; then
		tag="${BASH_REMATCH[5]}"
	fi
	echo $tag
}

assert() {
	echo "assert $1 == $2"
	if [ "$1" != "$2" ]; then
		echo "Assert fail $1 != $2"
		exit 1
	fi
}

#set default vars
HELP=false
INC_MAJOR=false
INC_MINOR=false
INC_PATCH=false
PRINT_MAJOR=false
PRINT_MINOR=false
PRINT_PATCH=false
PRINT_TAG=false

#parse args
for i in "$@"
do
	case "$i" in
	+major|^major)
		INC_MAJOR=true
		;;
	+minor|^minor)
		INC_MINOR=true
		;;
	+patch|^patch)
		INC_PATCH=true
		;;
	--print-major)
		PRINT_MAJOR=true
		;;
	--print-minor)
		PRINT_MINOR=true
		;;
	--print-patch)
		PRINT_PATCH=true
		;;
	--print-tag)
		PRINT_TAG=true
		;;
	-h|--help)
		output_help
		exit 0
		;;
	esac
done

#check for tests
if [ "$1" = '--tests' ] || [ "$1" = '--test' ]; then
	echo "Testing patterns that should fail..."
	
	VERSION="1~.2.3"
	MAJOR=$(getMajor $VERSION)
	assert "$MAJOR" ''

	VERSION="1.~2.3"
	MINOR=$(getMinor $VERSION)
	assert "$MINOR" ''

	VERSION="1.2~.3"
	MINOR=$(getMinor $VERSION)
	assert "$MINOR" ''

	VERSION="~1.2.3"
	MAJOR=$(getMajor $VERSION)
	assert "$MAJOR" ''

	echo "Testing patterns that should pass..."

	VERSION='1.2.3'
	FORCE=$(getForce $VERSION)
	MAJOR=$(getMajor $VERSION)
	MINOR=$(getMinor $VERSION)
	PATCH=$(getPatch $VERSION)
	TAG=$(getTag $VERSION)
	assert $FORCE ''
	assert $MAJOR '1'
	assert $MINOR '2'
	assert $PATCH '3'
	assert $TAG ''

	VERSION='10.20.30'
	FORCE=$(getForce $VERSION)
	MAJOR=$(getMajor $VERSION)
	MINOR=$(getMinor $VERSION)
	PATCH=$(getPatch $VERSION)
	TAG=$(getTag $VERSION)
	assert $FORCE ''
	assert $MAJOR '10'
	assert $MINOR '20'
	assert $PATCH '30'
	assert $TAG ''

	VERSION='100.200.300'
	FORCE=$(getForce $VERSION)
	MAJOR=$(getMajor $VERSION)
	MINOR=$(getMinor $VERSION)
	PATCH=$(getPatch $VERSION)
	TAG=$(getTag $VERSION)
	assert $FORCE ''
	assert $MAJOR '100'
	assert $MINOR '200'
	assert $PATCH '300'
	assert $TAG ''

	VERSION='!1.2.3'
	FORCE=$(getForce $VERSION)
	MAJOR=$(getMajor $VERSION)
	MINOR=$(getMinor $VERSION)
	PATCH=$(getPatch $VERSION)
	TAG=$(getTag $VERSION)
	assert $FORCE '!'
	assert $MAJOR '1'
	assert $MINOR '2'
	assert $PATCH '3'
	assert $TAG ''
	
	VERSION='!1.2.3-alpha'
	FORCE=$(getForce $VERSION)
	MAJOR=$(getMajor $VERSION)
	MINOR=$(getMinor $VERSION)
	PATCH=$(getPatch $VERSION)
	TAG=$(getTag $VERSION)
	assert $FORCE '!'
	assert $MAJOR '1'
	assert $MINOR '2'
	assert $PATCH '3'
	assert $TAG '-alpha'

	VERSION='!~.2.3'
	FORCE=$(getForce $VERSION)
	MAJOR=$(getMajor $VERSION)
	MINOR=$(getMinor $VERSION)
	PATCH=$(getPatch $VERSION)
	TAG=$(getTag $VERSION)
	assert $FORCE '!'
	assert $MAJOR '~'
	assert $MINOR '2'
	assert $PATCH '3'
	assert $TAG ''

	VERSION='!~.2.3-alpha'
	FORCE=$(getForce $VERSION)
	MAJOR=$(getMajor $VERSION)
	MINOR=$(getMinor $VERSION)
	PATCH=$(getPatch $VERSION)
	TAG=$(getTag $VERSION)
	assert $FORCE '!'
	assert $MAJOR '~'
	assert $MINOR '2'
	assert $PATCH '3'
	assert $TAG '-alpha'

	VERSION='!~.~.3'
	FORCE=$(getForce $VERSION)
	MAJOR=$(getMajor $VERSION)
	MINOR=$(getMinor $VERSION)
	PATCH=$(getPatch $VERSION)
	TAG=$(getTag $VERSION)
	assert $FORCE '!'
	assert $MAJOR '~'
	assert $MINOR '~'
	assert $PATCH '3'
	assert $TAG ''

	VERSION='!~.~.3-alpha'
	FORCE=$(getForce $VERSION)
	MAJOR=$(getMajor $VERSION)
	MINOR=$(getMinor $VERSION)
	PATCH=$(getPatch $VERSION)
	TAG=$(getTag $VERSION)
	assert $FORCE '!'
	assert $MAJOR '~'
	assert $MINOR '~'
	assert $PATCH '3'
	assert $TAG '-alpha'

	VERSION='!~.~.~'
	FORCE=$(getForce $VERSION)
	MAJOR=$(getMajor $VERSION)
	MINOR=$(getMinor $VERSION)
	PATCH=$(getPatch $VERSION)
	TAG=$(getTag $VERSION)
	assert $FORCE '!'
	assert $MAJOR '~'
	assert $MINOR '~'
	assert $PATCH '~'
	assert $TAG ''

	VERSION='!~.~.~-alpha'
	FORCE=$(getForce $VERSION)
	MAJOR=$(getMajor $VERSION)
	MINOR=$(getMinor $VERSION)
	PATCH=$(getPatch $VERSION)
	TAG=$(getTag $VERSION)
	assert $FORCE '!'
	assert $MAJOR '~'
	assert $MINOR '~'
	assert $PATCH '~'
	assert $TAG '-alpha'

	VERSION='~.2.3'
	FORCE=$(getForce $VERSION)
	MAJOR=$(getMajor $VERSION)
	MINOR=$(getMinor $VERSION)
	PATCH=$(getPatch $VERSION)
	TAG=$(getTag $VERSION)
	assert $FORCE ''
	assert $MAJOR '~'
	assert $MINOR '2'
	assert $PATCH '3'
	assert $TAG ''

	VERSION='~.2.3-alpha'
	FORCE=$(getForce $VERSION)
	MAJOR=$(getMajor $VERSION)
	MINOR=$(getMinor $VERSION)
	PATCH=$(getPatch $VERSION)
	TAG=$(getTag $VERSION)
	assert $FORCE ''
	assert $MAJOR '~'
	assert $MINOR '2'
	assert $PATCH '3'
	assert $TAG '-alpha'

	VERSION='~.~.3'
	FORCE=$(getForce $VERSION)
	MAJOR=$(getMajor $VERSION)
	MINOR=$(getMinor $VERSION)
	PATCH=$(getPatch $VERSION)
	TAG=$(getTag $VERSION)
	assert $FORCE ''
	assert $MAJOR '~'
	assert $MINOR '~'
	assert $PATCH '3'
	assert $TAG ''

	VERSION='~.~.3-alpha'
	FORCE=$(getForce $VERSION)
	MAJOR=$(getMajor $VERSION)
	MINOR=$(getMinor $VERSION)
	PATCH=$(getPatch $VERSION)
	TAG=$(getTag $VERSION)
	assert $FORCE ''
	assert $MAJOR '~'
	assert $MINOR '~'
	assert $PATCH '3'
	assert $TAG '-alpha'

	VERSION='~.~.~'
	FORCE=$(getForce $VERSION)
	MAJOR=$(getMajor $VERSION)
	MINOR=$(getMinor $VERSION)
	PATCH=$(getPatch $VERSION)
	TAG=$(getTag $VERSION)
	assert $FORCE ''
	assert $MAJOR '~'
	assert $MINOR '~'
	assert $PATCH '~'
	assert $TAG ''

	VERSION='~.~.~-alpha'
	FORCE=$(getForce $VERSION)
	MAJOR=$(getMajor $VERSION)
	MINOR=$(getMinor $VERSION)
	PATCH=$(getPatch $VERSION)
	TAG=$(getTag $VERSION)
	assert $FORCE ''
	assert $MAJOR '~'
	assert $MINOR '~'
	assert $PATCH '~'
	assert $TAG '-alpha'

	VERSION='1.2.~'
	FORCE=$(getForce $VERSION)
	MAJOR=$(getMajor $VERSION)
	MINOR=$(getMinor $VERSION)
	PATCH=$(getPatch $VERSION)
	TAG=$(getTag $VERSION)
	assert $FORCE ''
	assert $MAJOR '1'
	assert $MINOR '2'
	assert $PATCH '~'
	assert $TAG ''

	VERSION='1.2.~-alpha'
	FORCE=$(getForce $VERSION)
	MAJOR=$(getMajor $VERSION)
	MINOR=$(getMinor $VERSION)
	PATCH=$(getPatch $VERSION)
	TAG=$(getTag $VERSION)
	assert $FORCE ''
	assert $MAJOR '1'
	assert $MINOR '2'
	assert $PATCH '~'
	assert $TAG '-alpha'

	VERSION='1.~.~'
	FORCE=$(getForce $VERSION)
	MAJOR=$(getMajor $VERSION)
	MINOR=$(getMinor $VERSION)
	PATCH=$(getPatch $VERSION)
	TAG=$(getTag $VERSION)
	assert $FORCE ''
	assert $MAJOR '1'
	assert $MINOR '~'
	assert $PATCH '~'
	assert $TAG ''

	VERSION='1.~.~-alpha'
	FORCE=$(getForce $VERSION)
	MAJOR=$(getMajor $VERSION)
	MINOR=$(getMinor $VERSION)
	PATCH=$(getPatch $VERSION)
	TAG=$(getTag $VERSION)
	assert $FORCE ''
	assert $MAJOR '1'
	assert $MINOR '~'
	assert $PATCH '~'
	assert $TAG '-alpha'

	VERSION='!1.2.~+alpha'
	FORCE=$(getForce $VERSION)
	MAJOR=$(getMajor $VERSION)
	MINOR=$(getMinor $VERSION)
	PATCH=$(getPatch $VERSION)
	TAG=$(getTag $VERSION)
	assert $FORCE '!'
	assert $MAJOR '1'
	assert $MINOR '2'
	assert $PATCH '~'
	assert $TAG '+alpha'

	VERSION='1.2.~+alpha'
	FORCE=$(getForce $VERSION)
	MAJOR=$(getMajor $VERSION)
	MINOR=$(getMinor $VERSION)
	PATCH=$(getPatch $VERSION)
	TAG=$(getTag $VERSION)
	assert $FORCE ''
	assert $MAJOR '1'
	assert $MINOR '2'
	assert $PATCH '~'
	assert $TAG '+alpha'

	VERSION='1.2.~+-alpha.123'
	FORCE=$(getForce $VERSION)
	MAJOR=$(getMajor $VERSION)
	MINOR=$(getMinor $VERSION)
	PATCH=$(getPatch $VERSION)
	TAG=$(getTag $VERSION)
	assert $FORCE ''
	assert $MAJOR '1'
	assert $MINOR '2'
	assert $PATCH '~'
	assert $TAG '+-alpha.123'

	VERSION='1.2.~-+alpha.123'
	FORCE=$(getForce $VERSION)
	MAJOR=$(getMajor $VERSION)
	MINOR=$(getMinor $VERSION)
	PATCH=$(getPatch $VERSION)
	TAG=$(getTag $VERSION)
	assert $FORCE ''
	assert $MAJOR '1'
	assert $MINOR '2'
	assert $PATCH '~'
	assert $TAG '-+alpha.123'

	VERSION='1.2.~-+alpha.123-beta.94AF'
	FORCE=$(getForce $VERSION)
	MAJOR=$(getMajor $VERSION)
	MINOR=$(getMinor $VERSION)
	PATCH=$(getPatch $VERSION)
	TAG=$(getTag $VERSION)
	assert $FORCE ''
	assert $MAJOR '1'
	assert $MINOR '2'
	assert $PATCH '~'
	assert $TAG '-+alpha.123-beta.94AF'

	VERSION='1.2.~-+alpha.123-beta.94AF_A4fF.098-5'
	FORCE=$(getForce $VERSION)
	MAJOR=$(getMajor $VERSION)
	MINOR=$(getMinor $VERSION)
	PATCH=$(getPatch $VERSION)
	TAG=$(getTag $VERSION)
	assert $FORCE ''
	assert $MAJOR '1'
	assert $MINOR '2'
	assert $PATCH '~'
	assert $TAG '-+alpha.123-beta.94AF_A4fF.098-5'

	VERSION='1.2.~_-+alpha.123-beta.94AF_A4fF.098-5'
	FORCE=$(getForce $VERSION)
	MAJOR=$(getMajor $VERSION)
	MINOR=$(getMinor $VERSION)
	PATCH=$(getPatch $VERSION)
	TAG=$(getTag $VERSION)
	assert $FORCE ''
	assert $MAJOR '1'
	assert $MINOR '2'
	assert $PATCH '~'
	assert $TAG '_-+alpha.123-beta.94AF_A4fF.098-5'

	VERSION='1.2.~A40-+alpha.123-beta.94AF_A4fF.098-5'
	FORCE=$(getForce $VERSION)
	MAJOR=$(getMajor $VERSION)
	MINOR=$(getMinor $VERSION)
	PATCH=$(getPatch $VERSION)
	TAG=$(getTag $VERSION)
	assert $FORCE ''
	assert $MAJOR '1'
	assert $MINOR '2'
	assert $PATCH '~'
	assert $TAG 'A40-+alpha.123-beta.94AF_A4fF.098-5'

	VERSION='1.2.~.129FAD'
	FORCE=$(getForce $VERSION)
	MAJOR=$(getMajor $VERSION)
	MINOR=$(getMinor $VERSION)
	PATCH=$(getPatch $VERSION)
	TAG=$(getTag $VERSION)
	assert $FORCE ''
	assert $MAJOR '1'
	assert $MINOR '2'
	assert $PATCH '~'
	assert $TAG '.129FAD'

	echo "Testing script output fail..."

	output=$($0 'test')
	assert "$?" "1"

	output=$($0 '!1.2 +patch')
	assert "$?" "1"

	#TODO: Add more tests here to test the version regex before the script runs.

	echo "Testing script output..."

	output=$($0 1.2.3)
	assert $output "1.2.3"

	output=$($0 1.2.3 +major)
	assert $output "2.2.3"

	output=$($0 1.2.3 +minor)
	assert $output "1.3.3"

	output=$($0 1.2.3 +patch)
	assert $output "1.2.4"

	output=$($0 1.2.3 +major +minor)
	assert $output "2.3.3"

	output=$($0 1.2.3 +major +patch)
	assert $output "2.2.4"

	output=$($0 1.2.3 +minor +patch)
	assert $output "1.3.4"

	output=$($0 1.2.3 +major +minor +patch)
	assert $output "2.3.4"

	output=$($0 "~.2.3")
	assert $output "0.2.3"

	output=$($0 "~.~.3")
	assert $output "0.0.3"

	output=$($0 "~.~.~")
	assert $output "0.0.0"

	output=$($0 "!1.2.3")
	assert $output "1.2.3"

	output=$($0 "!1.2.3" +major)
	assert $output "1.2.3"

	output=$($0 "!1.2.3" +minor)
	assert $output "1.2.3"

	output=$($0 "!1.2.3" +patch)
	assert $output "1.2.3"

	output=$($0 "!1.2.3" +major +minor)
	assert $output "1.2.3"

	output=$($0 "!1.2.3" +major +patch)
	assert $output "1.2.3"

	output=$($0 "!1.2.3" +minor +patch)
	assert $output "1.2.3"

	output=$($0 "!1.2.3" +major +minor +patch)
	assert $output "1.2.3"

	output=$($0 "!~.2.3" +major)
	assert $output "0.2.3"

	output=$($0 "!1.~.3" +minor)
	assert $output "1.0.3"

	output=$($0 "!1.2.~" +patch)
	assert $output "1.2.0"

	output=$($0 "!~.~.~-alpha" +patch)
	assert $output "0.0.0-alpha"

	output=$($0 "!~.~.~+alpha" +patch)
	assert $output "0.0.0+alpha"

	output=$($0 "!~.~.~+-alpha" +patch)
	assert $output "0.0.0+-alpha"

	output=$($0 "!~.~.~_+-alpha" +patch)
	assert $output "0.0.0_+-alpha"

	output=$($0 "!~.~.~._+-alpha" +patch)
	assert $output "0.0.0._+-alpha"

	output=$($0 "!~.~.~.129AFD" +patch)
	assert $output "0.0.0.129AFD"

	output=$($0 "1.1.1.129AFD" +patch)
	assert $output "1.1.2.129AFD"

	output=$($0  "1.2.3" --print-patch)
	assert $output "3"

	output=$($0  "1.2.3" --print-major)
	assert $output "1"

	output=$($0  "1.2.3" --print-minor)
	assert $output "2"

	output=$($0  "1.2.3-alpha1.0934" --print-tag)
	assert $output "-alpha1.0934"

	output=$($0  "1.2.3.128AFD" --print-tag)
	assert $output ".128AFD"

	output=$($0 "1.~.3" --print-minor)
	assert $output "0"

	output=$($0 "!1.~.2" --print-minor +minor)
	assert $output "0"

	output=$($0 "1.1.~" --print-patch +patch)
	assert $output "0"

	output=$($0 "1.2.3" +patch --print-patch)
	assert $output "4"

	output=$($0 "1.2.3" --print-patch +patch)
	assert $output "4"

	echo "all tests passed"
	exit
fi

#grab version from args and validate it against regex
VERSION=$1
regex="^(!)?([0-9]*|~?)\.([0-9]*|~?)\.([0-9]*|~?)([-+0-9a-zA-Z\_\.]*)?$"
if [[  $VERSION =~ $regex ]]; then
	:
else
	exit 1
fi

#grab components from version
FORCE=$(getForce $VERSION)
MAJOR=$(getMajor $VERSION)
MINOR=$(getMinor $VERSION)
PATCH=$(getPatch $VERSION)
TAG=$(getTag $VERSION)

NEW_MAJOR=$MAJOR
NEW_MINOR=$MINOR
NEW_PATCH=$PATCH
MAJOR_ZEROED=''
MINOR_ZEROED=''
PATCH_ZEROED=''

#check for ~ to reset major to 0
if [ "$MAJOR" = "~" ]; then
	NEW_MAJOR='0'
	MAJOR_ZEROED='true'
fi

#check for ~ to reset minor to 0
if [ "$MINOR" = "~" ]; then
	NEW_MINOR='0'
	MINOR_ZEROED='true'
fi

#check for ~ to reset patch to 0
if [ "$NEW_PATCH" = "~" ]; then
	NEW_PATCH='0'
	PATCH_ZEROED='true'
fi

#increment major if force isn't present
if [ "$INC_MAJOR" = 'true' ] && [ -z $FORCE ] && [ -z $MAJOR_ZEROED ]; then
	NEW_MAJOR=$(($NEW_MAJOR + 1))
fi

#increment minor if force isn't present
if [ "$INC_MINOR" = 'true' ] && [ -z $FORCE ] && [ -z $MINOR_ZEROED ]; then
	NEW_MINOR=$(($NEW_MINOR + 1))
fi

#increment patch if force isn't present
if [ "$INC_PATCH" = "true" ] && [ -z $FORCE ] && [ -z $PATCH_ZEROED ]; then
	NEW_PATCH=$(($NEW_PATCH + 1))
fi

if [ "$PRINT_MAJOR" = true ]; then
	echo $NEW_MAJOR
	exit 0;
fi

if [ "$PRINT_MINOR" = true ]; then
	echo $NEW_MINOR
	exit 0
fi

if [ "$PRINT_PATCH" = true ]; then
	echo $NEW_PATCH
	exit 0
fi

if [ "$PRINT_TAG" = true ]; then
	echo $TAG
	exit 0
fi

#create new version
if [ "$TAG" ]; then
	echo "$NEW_MAJOR.$NEW_MINOR.$NEW_PATCH$TAG"
else
	echo "$NEW_MAJOR.$NEW_MINOR.$NEW_PATCH"
fi
